### ISSUE TITLE
the snake doesn't move idk why

### ISSUE THREAD

**Issue by OmarA32** [Terra-rian/snakecord#5] opened 2021-05-06 08:25 UTC

**Comment by Terra-rian** [comment] 2021-05-06 14:29
This isn't really descriptive, can you provide the code you used and what the error message(s) is/are, if any?

**Comment by OmarA32** [comment] 2021-05-06 18:06
sorry
-there are no errors at all.
-the message gets sent, and the bot reacts to it, and un-reacts when clicking on the reactions (as it should I think).
-the snake inside the embed doesn't move at all (I think that means the bot cant edit the embed true?).

https://imgur.com/a/uf0BHyn

edit: and hey, if you can, I think the embed would look way better if it was similar to this https://i.imgur.com/9LHkly1.png

**Comment by Terra-rian** [comment] 2021-05-06 21:17
- No errors, that's good. But are there any after you react to the arrow emotes on the embed message?
- Yes, the bot should remove reactions so you can react again if you would like to move the snake in the same direction twice.
- That's weird, I just tested it on my bot and everything seems to be working just fine. Are you sure it isn't lag or the bot not having access to the proper gateway intents?

If you could send a GIF of you trying to react and it not working/not editing the embed, that could help with debugging this.

**Comment by OmarA32** [comment] 2021-05-06 23:58
no errors after reacting, and I'm not using the "try" thing.
not a lag I'm sure
and idk whats a "proper gateway intents" lol, but my bot works well with everything I throw at it, and it has a music command that edits embeds, so I think there is no issue with the editing in my bot

video: https://imgur.com/a/nerpxZs

**Comment by Terra-rian** [comment] 2021-05-07 02:57
Can you show me how you initialize your bot client? I assume you're using Discord.js, you probably have something along the lines of `const client = new Discord.Client({ /* your options here */ })`. You will need [intents](https://discord.com/developers/docs/topics/gateway#gateway-intents) enabled to get reaction info, including who reacted, which is important for this package.

If you haven't done so already, try adding this line of code: `const intents = new Discord.Intents(Discord.Intents.ALL);` before the `client` initialization, and a `ws` object with the `intents: intents` property in the constructor. Also, go into your Discord Developer Portal, head into your bot application page, and scroll down until you see an option to enable privileged intents, and tick them to `on`.

If it still doesn't work, it might be a problem with your internet connection or something else on your side because I have tried recreating this multiple times by throttling my own bot's time delay between REST requests but everything still works fine.

**Comment by Terra-rian** [comment] 2021-05-08 21:04
I'll wait a week or so for a reply, if there's none I'll assume the issue was fixed, and close this issue here. You can reopen it with more details if it happens again after that time period.

**Comment by Terra-rian** [comment] 2021-05-17 15:26
Alright, there's been no reply for 9 days now, I'm going to assume that the issue is resolved. Please open another issue if this error keeps occuring, and you've made sure to follow the steps I've listed above.

**Closed as completed by Terra-rian** 2021-05-17 15:26 UTC
